-- ============================================================
-- DA Sheet Manager - Oracle Database Schema
-- Version: 1.0
-- Description: Complete schema for DA Sheet Manager module
-- ============================================================

-- ============================================================
-- SEQUENCES
-- ============================================================
CREATE SEQUENCE SEQ_DA_USERS START WITH 1 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_DA_TEMPLATES START WITH 1 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_DA_TEMPLATE_CATEGORIES START WITH 1 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_DA_TEMPLATE_PARAMS START WITH 1 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_DA_SHEETS START WITH 1 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_DA_SHEET_CATEGORIES START WITH 1 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_DA_SHEET_PARAMS START WITH 1 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_DA_VENDORS START WITH 1 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_DA_VENDOR_EVALS START WITH 1 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_DA_EVAL_FILES START WITH 1 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_DA_SHARED_ACCESS START WITH 1 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE SEQ_DA_AUDIT_LOG START WITH 1 INCREMENT BY 10 NOCACHE;

-- ============================================================
-- TABLES
-- ============================================================

-- Users (links to enterprise directory)
CREATE TABLE DA_USERS (
    USER_ID         NUMBER(10)     PRIMARY KEY,
    EMPLOYEE_CODE   VARCHAR2(50)   NOT NULL,
    FULL_NAME       VARCHAR2(200)  NOT NULL,
    EMAIL           VARCHAR2(255)  NOT NULL,
    PASSWORD_HASH   VARCHAR2(500),                -- NULL when SSO-only, populated for fallback auth
    MUST_CHANGE_PASSWORD NUMBER(1) DEFAULT 0 NOT NULL, -- 1 = user must change password on next login
    ROLE            VARCHAR2(20)   DEFAULT 'User' NOT NULL,
    IS_ACTIVE       NUMBER(1)      DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_DA_USER_EMPCODE UNIQUE (EMPLOYEE_CODE),
    CONSTRAINT UQ_DA_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_DA_USER_ROLE CHECK (ROLE IN ('Admin', 'User')),
    CONSTRAINT CHK_DA_USER_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT CHK_DA_USER_MUSTCHG CHECK (MUST_CHANGE_PASSWORD IN (0, 1))
);

-- Templates (admin-managed master definitions)
CREATE TABLE DA_TEMPLATES (
    TEMPLATE_ID   NUMBER(10)     PRIMARY KEY,
    NAME          VARCHAR2(200)  NOT NULL,
    DA_TYPE       VARCHAR2(30)   NOT NULL,
    DESCRIPTION   VARCHAR2(2000),
    STATUS        VARCHAR2(20)   DEFAULT 'Draft' NOT NULL,
    CREATED_BY    NUMBER(10)     NOT NULL,
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DA_TMPL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES DA_USERS(USER_ID),
    CONSTRAINT CHK_DA_TMPL_STATUS CHECK (STATUS IN ('Draft', 'Published'))
);

CREATE INDEX IDX_DA_TMPL_CREATED_BY ON DA_TEMPLATES(CREATED_BY);
CREATE INDEX IDX_DA_TMPL_STATUS ON DA_TEMPLATES(STATUS);

-- Template Categories (QCDMS groupings within templates)
CREATE TABLE DA_TEMPLATE_CATEGORIES (
    CATEGORY_ID   NUMBER(10)     PRIMARY KEY,
    TEMPLATE_ID   NUMBER(10)     NOT NULL,
    NAME          VARCHAR2(200)  NOT NULL,
    SORT_ORDER    NUMBER(3)      DEFAULT 0 NOT NULL,
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DA_TCAT_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES DA_TEMPLATES(TEMPLATE_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_DA_TCAT_TEMPLATE ON DA_TEMPLATE_CATEGORIES(TEMPLATE_ID);

-- Template Judgment Parameters (within categories)
CREATE TABLE DA_TEMPLATE_JUDGMENT_PARAMS (
    PARAM_ID      NUMBER(10)     PRIMARY KEY,
    CATEGORY_ID   NUMBER(10)     NOT NULL,
    NAME          VARCHAR2(300)  NOT NULL,
    WEIGHTAGE     NUMBER(2)      NOT NULL,
    SORT_ORDER    NUMBER(3)      DEFAULT 0 NOT NULL,
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DA_TPARAM_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES DA_TEMPLATE_CATEGORIES(CATEGORY_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_DA_TPARAM_CATEGORY ON DA_TEMPLATE_JUDGMENT_PARAMS(CATEGORY_ID);

-- DA Sheets (instances created from templates - snapshot pattern)
CREATE TABLE DA_SHEETS (
    SHEET_ID            NUMBER(10)     PRIMARY KEY,
    NAME                VARCHAR2(300)  NOT NULL,
    DA_TYPE             VARCHAR2(30)   NOT NULL,
    STATUS              VARCHAR2(20)   DEFAULT 'Draft' NOT NULL,
    SOURCE_TEMPLATE_ID  NUMBER(10)     NOT NULL,
    VERSION             NUMBER(5)      DEFAULT 1 NOT NULL,
    NOTES               VARCHAR2(4000),
    CREATED_BY          NUMBER(10)     NOT NULL,
    CREATED_AT          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    SUBMITTED_AT        TIMESTAMP,
    DUPLICATED_FROM     NUMBER(10),
    CONSTRAINT FK_DA_SHEET_TEMPLATE FOREIGN KEY (SOURCE_TEMPLATE_ID) REFERENCES DA_TEMPLATES(TEMPLATE_ID),
    CONSTRAINT FK_DA_SHEET_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES DA_USERS(USER_ID),
    CONSTRAINT FK_DA_SHEET_DUP_FROM FOREIGN KEY (DUPLICATED_FROM) REFERENCES DA_SHEETS(SHEET_ID),
    CONSTRAINT CHK_DA_SHEET_STATUS CHECK (STATUS IN ('Draft', 'Final'))
);

CREATE INDEX IDX_DA_SHEET_CREATED_BY ON DA_SHEETS(CREATED_BY);
CREATE INDEX IDX_DA_SHEET_STATUS ON DA_SHEETS(STATUS);
CREATE INDEX IDX_DA_SHEET_TEMPLATE ON DA_SHEETS(SOURCE_TEMPLATE_ID);

-- Sheet Categories (frozen snapshot from template, customized in Step 3)
CREATE TABLE DA_SHEET_CATEGORIES (
    SHEET_CATEGORY_ID   NUMBER(10)     PRIMARY KEY,
    SHEET_ID            NUMBER(10)     NOT NULL,
    SOURCE_CATEGORY_ID  NUMBER(10),
    NAME                VARCHAR2(200)  NOT NULL,
    SORT_ORDER          NUMBER(3)      DEFAULT 0 NOT NULL,
    CONSTRAINT FK_DA_SCAT_SHEET FOREIGN KEY (SHEET_ID) REFERENCES DA_SHEETS(SHEET_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_DA_SCAT_SHEET ON DA_SHEET_CATEGORIES(SHEET_ID);

-- Sheet Judgment Parameters (frozen snapshot, customized weightages)
CREATE TABLE DA_SHEET_JUDGMENT_PARAMS (
    SHEET_PARAM_ID      NUMBER(10)     PRIMARY KEY,
    SHEET_CATEGORY_ID   NUMBER(10)     NOT NULL,
    SOURCE_PARAM_ID     NUMBER(10),
    NAME                VARCHAR2(300)  NOT NULL,
    WEIGHTAGE           NUMBER(2)      NOT NULL,
    SORT_ORDER          NUMBER(3)      DEFAULT 0 NOT NULL,
    CONSTRAINT FK_DA_SPARAM_SCAT FOREIGN KEY (SHEET_CATEGORY_ID) REFERENCES DA_SHEET_CATEGORIES(SHEET_CATEGORY_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_DA_SPARAM_SCAT ON DA_SHEET_JUDGMENT_PARAMS(SHEET_CATEGORY_ID);

-- Vendors (attached to specific DA sheets)
CREATE TABLE DA_VENDORS (
    VENDOR_ID     NUMBER(10)     PRIMARY KEY,
    SHEET_ID      NUMBER(10)     NOT NULL,
    NAME          VARCHAR2(300)  NOT NULL,
    SORT_ORDER    NUMBER(3)      DEFAULT 0 NOT NULL,
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DA_VENDOR_SHEET FOREIGN KEY (SHEET_ID) REFERENCES DA_SHEETS(SHEET_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_DA_VENDOR_SHEET ON DA_VENDORS(SHEET_ID);

-- Vendor Evaluations (per-vendor, per-parameter scoring)
CREATE TABLE DA_VENDOR_EVALUATIONS (
    EVAL_ID         NUMBER(10)     PRIMARY KEY,
    VENDOR_ID       NUMBER(10)     NOT NULL,
    SHEET_PARAM_ID  NUMBER(10)     NOT NULL,
    EVAL_SCORE      NUMBER(2),
    VENDOR_COMMENT  VARCHAR2(2000),
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DA_EVAL_VENDOR FOREIGN KEY (VENDOR_ID) REFERENCES DA_VENDORS(VENDOR_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DA_EVAL_PARAM FOREIGN KEY (SHEET_PARAM_ID) REFERENCES DA_SHEET_JUDGMENT_PARAMS(SHEET_PARAM_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_DA_EVAL_SCORE CHECK (EVAL_SCORE BETWEEN 0 AND 10),
    CONSTRAINT UQ_DA_VENDOR_PARAM UNIQUE (VENDOR_ID, SHEET_PARAM_ID)
);

CREATE INDEX IDX_DA_EVAL_VENDOR ON DA_VENDOR_EVALUATIONS(VENDOR_ID);
CREATE INDEX IDX_DA_EVAL_PARAM ON DA_VENDOR_EVALUATIONS(SHEET_PARAM_ID);

-- Evaluation File Attachments (stored as Oracle BLOBs)
CREATE TABLE DA_EVAL_FILES (
    FILE_ID           NUMBER(10)     PRIMARY KEY,
    EVAL_ID           NUMBER(10)     NOT NULL,
    ORIGINAL_FILENAME VARCHAR2(500)  NOT NULL,
    CONTENT_TYPE      VARCHAR2(100)  NOT NULL,
    FILE_SIZE_BYTES   NUMBER(15)     NOT NULL,
    FILE_DATA         BLOB           NOT NULL,
    UPLOADED_BY       NUMBER(10)     NOT NULL,
    UPLOADED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DA_FILE_EVAL FOREIGN KEY (EVAL_ID) REFERENCES DA_VENDOR_EVALUATIONS(EVAL_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DA_FILE_UPLOADER FOREIGN KEY (UPLOADED_BY) REFERENCES DA_USERS(USER_ID)
);

CREATE INDEX IDX_DA_FILE_EVAL ON DA_EVAL_FILES(EVAL_ID);

-- Shared Access (share DA sheets with other users)
CREATE TABLE DA_SHARED_ACCESS (
    SHARE_ID          NUMBER(10)     PRIMARY KEY,
    SHEET_ID          NUMBER(10)     NOT NULL,
    SHARED_WITH_EMAIL VARCHAR2(255)  NOT NULL,
    SHARED_WITH_USER  NUMBER(10),
    ACCESS_LEVEL      VARCHAR2(10)   DEFAULT 'view' NOT NULL,
    SHARED_BY         NUMBER(10)     NOT NULL,
    SHARED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DA_SHARE_SHEET FOREIGN KEY (SHEET_ID) REFERENCES DA_SHEETS(SHEET_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DA_SHARE_BY FOREIGN KEY (SHARED_BY) REFERENCES DA_USERS(USER_ID),
    CONSTRAINT FK_DA_SHARE_WITH FOREIGN KEY (SHARED_WITH_USER) REFERENCES DA_USERS(USER_ID),
    CONSTRAINT CHK_DA_ACCESS_LEVEL CHECK (ACCESS_LEVEL IN ('view', 'edit')),
    CONSTRAINT UQ_DA_SHARE_SHEET_EMAIL UNIQUE (SHEET_ID, SHARED_WITH_EMAIL)
);

CREATE INDEX IDX_DA_SHARE_SHEET ON DA_SHARED_ACCESS(SHEET_ID);
CREATE INDEX IDX_DA_SHARE_EMAIL ON DA_SHARED_ACCESS(SHARED_WITH_EMAIL);

-- Audit Log (enterprise compliance trail)
CREATE TABLE DA_AUDIT_LOG (
    LOG_ID          NUMBER(10)     PRIMARY KEY,
    ENTITY_TYPE     VARCHAR2(50)   NOT NULL,
    ENTITY_ID       NUMBER(10)     NOT NULL,
    ACTION          VARCHAR2(30)   NOT NULL,
    OLD_VALUES      CLOB,
    NEW_VALUES      CLOB,
    PERFORMED_BY    NUMBER(10)     NOT NULL,
    PERFORMED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DA_AUDIT_USER FOREIGN KEY (PERFORMED_BY) REFERENCES DA_USERS(USER_ID)
);

CREATE INDEX IDX_DA_AUDIT_ENTITY ON DA_AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_DA_AUDIT_DATE ON DA_AUDIT_LOG(PERFORMED_AT);

-- ============================================================
-- SEED DATA: Default Templates
-- ============================================================

-- Insert admin user (placeholder - will be replaced by enterprise SSO mapping)
-- Password: Admin@123  |  The SHA-256/Base64 hash below is accepted by the
-- application and auto-upgraded to BCrypt on the admin's first successful login.
INSERT INTO DA_USERS (USER_ID, EMPLOYEE_CODE, FULL_NAME, EMAIL, PASSWORD_HASH, MUST_CHANGE_PASSWORD, ROLE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SEQ_DA_USERS.NEXTVAL, 'ADMIN001', 'System Administrator', 'admin@company.com',
        '6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=',
        1, 'Admin', 1, SYSTIMESTAMP, SYSTIMESTAMP);
-- Default password: Admin@123 (must be changed on first login)
